### ISSUE TITLE
Unicode bug  in pandas.lib.write_csv_rows 

### ISSUE THREAD

**Issue by azu-p** [panalysis/Google2Pandas#6]
{'metrics': ['pageviews', 'uniquePageviews'], 'max_results': 10000, 'dimensions'
: ['date', 'dimension1'], 'end_date': '2015-11-30', 'ids': 'XXX', 'start_index': 1, 'start_date': '2015-11-01'}

Traceback (most recent call last):
  File "dataExtractor2.py", line 97, in <module>
    df.to_csv(filename)
  File "C:\Python27\lib\site-packages\pandas\core\frame.py", line 1332, in to_csv
    formatter.save()
  File "C:\Python27\lib\site-packages\pandas\core\format.py", line 1506, in save

```
self._save()
```

  File "C:\Python27\lib\site-packages\pandas\core\format.py", line 1606, in _save
    self._save_chunk(start_i, end_i)
  File "C:\Python27\lib\site-packages\pandas\core\format.py", line 1633, in _save_chunk
    lib.write_csv_rows(self.data, ix, self.nlevels, self.cols, self.writer)
  File "pandas\lib.pyx", line 1056, in pandas.lib.write_csv_rows (pandas\lib.c:1
9462)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2006' in position 1
: ordinal not in range(128)

**Comment by azu-p** [comment]
Couldn't replicate the issue.
